// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDdq9PDNYilN3godVDtbjdECp_9HryzmM',
    appId: '1:400038466330:web:aa50038e1d16b4dd02d2a3',
    messagingSenderId: '400038466330',
    projectId: 'alzheimerapp-8ba1b',
    authDomain: 'alzheimerapp-8ba1b.firebaseapp.com',
    storageBucket: 'alzheimerapp-8ba1b.firebasestorage.app',
    measurementId: 'G-4359PH89RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoaNxcr5ZofZOFQZz7vqU8Wrgb20FZ6lY',
    appId: '1:400038466330:android:3519fd1b94f75a9602d2a3',
    messagingSenderId: '400038466330',
    projectId: 'alzheimerapp-8ba1b',
    storageBucket: 'alzheimerapp-8ba1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhbGaRVT3uJzcO7OFsgUGui85fS-9So14',
    appId: '1:400038466330:ios:03c36c15e745630f02d2a3',
    messagingSenderId: '400038466330',
    projectId: 'alzheimerapp-8ba1b',
    storageBucket: 'alzheimerapp-8ba1b.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhbGaRVT3uJzcO7OFsgUGui85fS-9So14',
    appId: '1:400038466330:ios:03c36c15e745630f02d2a3',
    messagingSenderId: '400038466330',
    projectId: 'alzheimerapp-8ba1b',
    storageBucket: 'alzheimerapp-8ba1b.firebasestorage.app',
    iosBundleId: 'com.example.alzheimerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDdq9PDNYilN3godVDtbjdECp_9HryzmM',
    appId: '1:400038466330:web:d33c9f33e64a4b2902d2a3',
    messagingSenderId: '400038466330',
    projectId: 'alzheimerapp-8ba1b',
    authDomain: 'alzheimerapp-8ba1b.firebaseapp.com',
    storageBucket: 'alzheimerapp-8ba1b.firebasestorage.app',
    measurementId: 'G-VPME1DGZMH',
  );
}
